main: cat.math.shopsigns.ShopSigns
name: ShopSigns
version: 1.0
author: Rowan McKee
api-version: 1.14

depend: [Essentials, Vault]

commands:
   shop:
      description: Configure shop details
      usage: /shop
      permission: shopsigns.shop
      permission-message: You do not have permission.
   shopsigns:
      description: Admin commands
      usage: /shopsigns [options]
      permission: shopsigns.admin
      permission-message: You do not have permission.
   find:
      description: Find buy or sell signs.
      usage: /find [buy|sell] [item] <player>
      aliases: [findshop, fs]
      permission: shopsigns.find
      permission-message: You do not have permission.

permissions:
   shopsigns.*:
      default: op
   shopsigns.bypass-privacy:
      default: op
   shopsigns.break.other:
      default: op
   shopsigns.shop:
      default: true
   shopsigns.find:
      default: true
   shopsigns.admin:
      default: op
   shopsigns.makeshop:
      default: true
   shopsigns.buy:
      default: true
   shopsigns.sell:
      default: true
   shopsigns.adminshop-buy:
      default: true
   shopsigns.adminshop-sell:
      default: true   